#!/usr/bin/env python3
"""
Build pips_b64.json from the local mana-master SVG icon library.

Converts Andrew Gioia's Mana font SVGs into base64-encoded PNGs with
authentic MTG-colored circle backgrounds — matching real card pip colors.

This replaces the need to download from Scryfall or MTG Wiki for:
- Core mana symbols (W, U, B, R, G, C, colorless numbers, etc.)
- Loyalty shapes (loyalty-up, loyalty-down, loyalty-zero, loyalty-start)
- Tap/untap, energy, snow, phyrexian mana, X/Y/Z
- Counter symbols

Hybrid mana (W/U, U/R, etc.) is generated by compositing two half-circles
with appropriate colors and overlaying both mana glyphs (split diagonally).

Usage:
    python build_pips_from_mana.py [--force] [--size 128]
"""

import argparse
import base64
import io
import json
import re
import sys
from pathlib import Path

try:
    import cairosvg
except ImportError:
    print("ERROR: cairosvg required. Install with: pip install cairosvg")
    sys.exit(1)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
MANA_SVG_DIR = Path(__file__).parent / "mana-master" / "svg"
PIPS_DIR = Path(__file__).parent / "shared" / "pips"
PIPS_B64_PATH = PIPS_DIR / "pips_b64.json"
LOYALTY_MAP_PATH = PIPS_DIR / "loyalty_map.json"

# ---------------------------------------------------------------------------
# Authentic MTG mana pip colors
# Each colored mana symbol has a distinct circle background and glyph color,
# matching the official Wizards of the Coast card designs.
# ---------------------------------------------------------------------------
PIP_COLORS = {
    # (circle_bg, circle_border, glyph_fill)
    'W': ('#F9F5D7', '#C9B95C', '#1A1410'),   # White: warm ivory circle, dark glyph
    'U': ('#AAE0FA', '#5B93C0', '#1A1410'),   # Blue: sky blue circle
    'B': ('#CBC2BF', '#5A5050', '#1A1410'),   # Black: warm gray circle
    'R': ('#F9AA8F', '#C05840', '#1A1410'),   # Red: salmon/coral circle
    'G': ('#9BD3AE', '#408050', '#1A1410'),   # Green: sage green circle
    'C': ('#D0CCC8', '#908880', '#1A1410'),   # Colorless: silver gray circle
    'S': ('#D8ECF8', '#6090B0', '#1A1410'),   # Snow: icy blue circle
    'E': ('#F0D868', '#C0A030', '#1A1410'),   # Energy: golden yellow circle
    'T': ('#D0CCC8', '#908880', '#1A1410'),   # Tap: gray circle
    'Q': ('#D0CCC8', '#908880', '#1A1410'),   # Untap: gray circle
    'X': ('#D0CCC8', '#908880', '#1A1410'),   # X: gray circle
    'Y': ('#D0CCC8', '#908880', '#1A1410'),   # Y: gray circle
    'Z': ('#D0CCC8', '#908880', '#1A1410'),   # Z: gray circle
    'P': ('#D0CCC8', '#908880', '#1A1410'),   # Phyrexian: gray circle
}

# Numeric mana gets the generic colorless treatment
GENERIC_COLORS = ('#D0CCC8', '#908880', '#1A1410')

# Loyalty shapes get dark fill (text is overlaid in white by the renderer)
LOYALTY_COLORS = ('#222222', '#111111', '#FFFFFF')

# Counter symbols
COUNTER_COLORS = ('#333333', '#222222', '#FFFFFF')

# Type symbols
TYPE_COLORS = ('#D0CCC8', '#908880', '#1A1410')

# ---------------------------------------------------------------------------
# Symbol mapping: mana-master filename -> pips_b64 key
# ---------------------------------------------------------------------------

# Core mana symbols
MANA_SYMBOLS = {
    'w': 'W',
    'u': 'U',
    'b': 'B',
    'r': 'R',
    'g': 'G',
    'c': 'C',
    's': 'S',       # Snow mana
    'e': 'E',       # Energy
    'x': 'X',
    'y': 'Y',
    'z': 'Z',
    'p': 'P',       # Phyrexian generic
    'tap': 'T',
    'untap': 'Q',   # Untap symbol
}

# Numeric mana (0-20 plus specials)
NUMERIC_MANA = {str(i): str(i) for i in range(21)}
NUMERIC_MANA['100'] = '100'
NUMERIC_MANA['1000000'] = '1000000'

# Loyalty shapes — arrow/shield outlines
LOYALTY_SYMBOLS = {
    'loyalty-up': 'loyalty_up',
    'loyalty-down': 'loyalty_down',
    'loyalty-zero': 'loyalty_zero',
    'loyalty-start': 'loyalty_start',
}

# Counter symbols
COUNTER_SYMBOLS = {
    'counter-loyalty': 'counter_loyalty',
    'counter-plus': 'counter_plus',
    'counter-minus': 'counter_minus',
    'counter-shield': 'counter_shield',
}

# Card type symbols
TYPE_SYMBOLS = {
    'artifact': 'type_artifact',
    'creature': 'type_creature',
    'enchantment': 'type_enchantment',
    'instant': 'type_instant',
    'land': 'type_land',
    'planeswalker': 'type_planeswalker',
    'sorcery': 'type_sorcery',
    'token': 'type_token',
    'saga': 'type_saga',
}

# ---------------------------------------------------------------------------
# Hybrid mana definitions
# Each hybrid pair: (top_color_key, bottom_color_key)
# These match the official MTG hybrid mana ordering (WUBRG circle order)
# ---------------------------------------------------------------------------
HYBRID_PAIRS = {
    'W/U': ('W', 'U'),  # Azorius
    'W/B': ('W', 'B'),  # Orzhov
    'U/B': ('U', 'B'),  # Dimir
    'U/R': ('U', 'R'),  # Izzet
    'B/R': ('B', 'R'),  # Rakdos
    'B/G': ('B', 'G'),  # Golgari
    'R/W': ('R', 'W'),  # Boros
    'R/G': ('R', 'G'),  # Gruul
    'G/W': ('G', 'W'),  # Selesnya
    'G/U': ('G', 'U'),  # Simic
    # Twobrid (2/color)
    '2/W': ('C', 'W'),
    '2/U': ('C', 'U'),
    '2/B': ('C', 'B'),
    '2/R': ('C', 'R'),
    '2/G': ('C', 'G'),
}

# Official mana colors from the Mana font CSS variables
HYBRID_FILL_COLORS = {
    'W': '#fdfbce',
    'U': '#bcdaf7',
    'B': '#a7999e',
    'R': '#f19b79',
    'G': '#9fcba6',
    'C': '#d0c6bb',
}

# Border colors for hybrid halves (slightly darker than fill)
HYBRID_BORDER_COLORS = {
    'W': '#C9B95C',
    'U': '#5B93C0',
    'B': '#5A5050',
    'R': '#C05840',
    'G': '#408050',
    'C': '#908880',
}

# Combine all mappings
ALL_SYMBOLS = {}
ALL_SYMBOLS.update(MANA_SYMBOLS)
ALL_SYMBOLS.update(NUMERIC_MANA)
ALL_SYMBOLS.update(LOYALTY_SYMBOLS)
ALL_SYMBOLS.update(COUNTER_SYMBOLS)
ALL_SYMBOLS.update(TYPE_SYMBOLS)


def _get_pip_colors(svg_name: str, pip_key: str):
    """Return (circle_bg, circle_border, glyph_fill) for a given symbol."""
    if svg_name.startswith('loyalty-'):
        return LOYALTY_COLORS
    if svg_name.startswith('counter-'):
        return COUNTER_COLORS
    if pip_key in PIP_COLORS:
        return PIP_COLORS[pip_key]
    # Numeric mana or other generic
    if pip_key.isdigit() or pip_key in ('100', '1000000'):
        return GENERIC_COLORS
    if svg_name in TYPE_SYMBOLS:
        return TYPE_COLORS
    return GENERIC_COLORS


def _build_composite_svg(glyph_svg_content: str, circle_bg: str,
                          circle_border: str, glyph_fill: str,
                          needs_circle: bool = True) -> str:
    """Build a composite SVG with a colored circle background + glyph overlay.

    The mana-master glyphs are 32×32 viewBox with fill="#444".
    We create a new SVG with:
    1. A filled circle background (authentic MTG pip color)
    2. A dark border ring for definition
    3. The glyph centered on top, slightly scaled down to fit inside the circle

    For loyalty/counter shapes, we skip the circle background.
    """
    # Extract just the <path> data from the glyph SVG
    import xml.etree.ElementTree as ET
    try:
        root = ET.fromstring(glyph_svg_content)
        ns = '{http://www.w3.org/2000/svg}'
        path_el = root.find(f'.//{ns}path')
        if path_el is None:
            path_el = root.find('.//path')
        if path_el is None:
            return glyph_svg_content  # fallback: return raw SVG
        path_d = path_el.get('d', '')
    except Exception:
        return glyph_svg_content

    size = 128  # internal viewBox size for the composite
    cx = size / 2
    cy = size / 2

    if needs_circle:
        # Glyph scales: the 32×32 glyph path gets scaled to fit inside the circle
        # Leave ~20% padding so the glyph doesn't touch the circle edge
        glyph_scale = (size * 0.60) / 32.0  # scale 32→~77px
        glyph_offset_x = (size - 32 * glyph_scale) / 2
        glyph_offset_y = (size - 32 * glyph_scale) / 2

        svg = f'''<?xml version="1.0" encoding="UTF-8"?>
<svg width="{size}" height="{size}" viewBox="0 0 {size} {size}"
     xmlns="http://www.w3.org/2000/svg">
  <!-- Colored circle background -->
  <circle cx="{cx}" cy="{cy}" r="{cx - 2}" fill="{circle_bg}"/>
  <circle cx="{cx}" cy="{cy}" r="{cx - 2}" fill="none"
          stroke="{circle_border}" stroke-width="3"/>
  <!-- Mana glyph -->
  <g transform="translate({glyph_offset_x:.1f},{glyph_offset_y:.1f}) scale({glyph_scale:.4f})">
    <path d="{path_d}" fill="{glyph_fill}"/>
  </g>
</svg>'''
    else:
        # No circle — just the shape (loyalty, counters)
        glyph_scale = size / 32.0
        svg = f'''<?xml version="1.0" encoding="UTF-8"?>
<svg width="{size}" height="{size}" viewBox="0 0 {size} {size}"
     xmlns="http://www.w3.org/2000/svg">
  <g transform="scale({glyph_scale:.4f})">
    <path d="{path_d}" fill="{glyph_fill}"/>
  </g>
</svg>'''

    return svg


def _build_hybrid_svg(top_color_key: str, bottom_color_key: str,
                       top_glyph_svg: str, bottom_glyph_svg: str) -> str:
    """Build a hybrid mana pip with split circle (top-left / bottom-right diagonal).

    Real MTG hybrid mana pips have:
    - A circle split diagonally (top-left = first color, bottom-right = second color)
    - The first mana symbol glyph in the top-left half
    - The second mana symbol glyph in the bottom-right half
    - A dark border ring around the circle
    - A thin diagonal line separating the halves
    """
    import xml.etree.ElementTree as ET

    def extract_path_d(svg_text):
        try:
            root = ET.fromstring(svg_text)
            ns = '{http://www.w3.org/2000/svg}'
            path_el = root.find(f'.//{ns}path')
            if path_el is None:
                path_el = root.find('.//path')
            return path_el.get('d', '') if path_el is not None else ''
        except Exception:
            return ''

    top_path_d = extract_path_d(top_glyph_svg)
    bottom_path_d = extract_path_d(bottom_glyph_svg)

    if not top_path_d or not bottom_path_d:
        return ''

    size = 128
    cx = size / 2
    cy = size / 2
    r = cx - 2

    top_fill = HYBRID_FILL_COLORS.get(top_color_key, '#D0CCC8')
    bottom_fill = HYBRID_FILL_COLORS.get(bottom_color_key, '#D0CCC8')
    border = '#333'

    # Glyph scaling: smaller since two glyphs share the space
    glyph_scale = (size * 0.42) / 32.0
    glyph_px = 32 * glyph_scale  # actual glyph pixel size

    # Position top glyph in upper-left area, bottom glyph in lower-right area
    top_glyph_x = cx - glyph_px * 0.75
    top_glyph_y = cy - glyph_px * 0.85
    bottom_glyph_x = cx - glyph_px * 0.25
    bottom_glyph_y = cy - glyph_px * 0.15

    glyph_fill = '#1A1410'

    svg = f'''<?xml version="1.0" encoding="UTF-8"?>
<svg width="{size}" height="{size}" viewBox="0 0 {size} {size}"
     xmlns="http://www.w3.org/2000/svg">
  <defs>
    <!-- Clip path for the top-left half (above diagonal) -->
    <clipPath id="topHalf">
      <polygon points="0,0 {size},0 0,{size}"/>
    </clipPath>
    <!-- Clip path for the bottom-right half (below diagonal) -->
    <clipPath id="bottomHalf">
      <polygon points="{size},0 {size},{size} 0,{size}"/>
    </clipPath>
    <!-- Circular clip for the whole pip -->
    <clipPath id="circleClip">
      <circle cx="{cx}" cy="{cy}" r="{r}"/>
    </clipPath>
  </defs>
  <!-- Full circle background clipped to circle shape -->
  <g clip-path="url(#circleClip)">
    <!-- Top-left half -->
    <g clip-path="url(#topHalf)">
      <rect width="{size}" height="{size}" fill="{top_fill}"/>
    </g>
    <!-- Bottom-right half -->
    <g clip-path="url(#bottomHalf)">
      <rect width="{size}" height="{size}" fill="{bottom_fill}"/>
    </g>
    <!-- Diagonal separator line -->
    <line x1="0" y1="{size}" x2="{size}" y2="0"
          stroke="#555" stroke-width="1.5" opacity="0.4"/>
  </g>
  <!-- Border ring -->
  <circle cx="{cx}" cy="{cy}" r="{r}" fill="none"
          stroke="{border}" stroke-width="3.5"/>
  <!-- Top glyph (first color's mana symbol, upper-left) -->
  <g transform="translate({top_glyph_x:.1f},{top_glyph_y:.1f}) scale({glyph_scale:.4f})">
    <path d="{top_path_d}" fill="{glyph_fill}"/>
  </g>
  <!-- Bottom glyph (second color's mana symbol, lower-right) -->
  <g transform="translate({bottom_glyph_x:.1f},{bottom_glyph_y:.1f}) scale({glyph_scale:.4f})">
    <path d="{bottom_path_d}" fill="{glyph_fill}"/>
  </g>
</svg>'''
    return svg


def svg_to_b64_png(svg_content: str, size: int = 128) -> str:
    """Convert SVG content string to a base64-encoded PNG."""
    png_data = cairosvg.svg2png(
        bytestring=svg_content.encode('utf-8'),
        output_width=size,
        output_height=size,
    )
    return base64.b64encode(png_data).decode('ascii')


def build_pips(size: int = 128, force: bool = False) -> dict:
    """Build pips_b64.json from mana-master SVGs with colored backgrounds.

    Returns the pips dict and saves to disk.
    """
    if not MANA_SVG_DIR.exists():
        print(f"ERROR: mana-master SVG directory not found: {MANA_SVG_DIR}")
        sys.exit(1)

    PIPS_DIR.mkdir(parents=True, exist_ok=True)

    # Load existing pips (preserve previously built symbols)
    existing = {}
    if PIPS_B64_PATH.exists() and not force:
        with open(PIPS_B64_PATH) as f:
            existing = json.load(f)
        print(f"[mana] Loaded {len(existing)} existing symbols from cache")

    pips = dict(existing)  # start with existing (preserves previously built symbols)
    converted = 0
    skipped = 0

    for svg_name, pip_key in ALL_SYMBOLS.items():
        svg_path = MANA_SVG_DIR / f"{svg_name}.svg"
        if not svg_path.exists():
            print(f"  SKIP {svg_name}.svg — not found")
            skipped += 1
            continue

        # Get authentic MTG colors for this symbol
        circle_bg, circle_border, glyph_fill = _get_pip_colors(svg_name, pip_key)

        # Loyalty and counter shapes don't get circle backgrounds
        needs_circle = not (svg_name.startswith('loyalty-') or
                           svg_name.startswith('counter-') or
                           svg_name in TYPE_SYMBOLS)

        try:
            raw_svg = svg_path.read_text()
            composite_svg = _build_composite_svg(
                raw_svg, circle_bg, circle_border, glyph_fill,
                needs_circle=needs_circle
            )
            b64 = svg_to_b64_png(composite_svg, size=size)
            pips[pip_key] = b64
            converted += 1
        except Exception as e:
            print(f"  ERROR converting {svg_name}.svg: {e}")
            skipped += 1

    # --- Build hybrid mana pips ---
    hybrid_converted = 0
    # Map color keys to their SVG filenames in mana-master
    color_svg_files = {
        'W': 'w.svg', 'U': 'u.svg', 'B': 'b.svg',
        'R': 'r.svg', 'G': 'g.svg', 'C': 'c.svg',
    }

    for hybrid_key, (top_key, bottom_key) in HYBRID_PAIRS.items():
        # Store under both "U/R" and sanitized "U_R" keys
        safe_key = hybrid_key.replace('/', '_')

        top_svg_path = MANA_SVG_DIR / color_svg_files.get(top_key, '')
        bottom_svg_path = MANA_SVG_DIR / color_svg_files.get(bottom_key, '')

        if not top_svg_path.exists() or not bottom_svg_path.exists():
            print(f"  SKIP hybrid {hybrid_key} — missing glyph SVGs")
            continue

        try:
            # For twobrid (2/X), use the "2" numeral glyph for the top
            if hybrid_key.startswith('2/'):
                two_svg_path = MANA_SVG_DIR / '2.svg'
                if two_svg_path.exists():
                    top_svg_content = two_svg_path.read_text()
                else:
                    top_svg_content = top_svg_path.read_text()
            else:
                top_svg_content = top_svg_path.read_text()
            bottom_svg_content = bottom_svg_path.read_text()

            hybrid_svg = _build_hybrid_svg(
                top_key, bottom_key,
                top_svg_content, bottom_svg_content
            )
            if hybrid_svg:
                b64 = svg_to_b64_png(hybrid_svg, size=size)
                pips[hybrid_key] = b64  # Store as "U/R"
                pips[safe_key] = b64    # Also store as "U_R"
                hybrid_converted += 1
        except Exception as e:
            print(f"  ERROR building hybrid {hybrid_key}: {e}")

    if hybrid_converted:
        print(f"[mana] Built {hybrid_converted} hybrid mana symbols")

    # Save pips_b64.json
    with open(PIPS_B64_PATH, 'w') as f:
        json.dump(pips, f)
    print(f"[mana] Saved {len(pips)} symbols to {PIPS_B64_PATH}")
    print(f"       ({converted} core + {hybrid_converted} hybrid from mana-master, "
          f"{len(pips) - converted - hybrid_converted * 2} preserved from cache)")

    # Build loyalty map
    loyalty_map = {
        'LOYALTY_UP': 'loyalty_up',
        'LOYALTY_DOWN': 'loyalty_down',
        'LOYALTY_ZERO': 'loyalty_zero',
        'LOYALTY_START': 'loyalty_start',
        'LOYALTY': 'loyalty_start',
    }
    with open(LOYALTY_MAP_PATH, 'w') as f:
        json.dump(loyalty_map, f, indent=2)
    print(f"[mana] Saved loyalty map to {LOYALTY_MAP_PATH}")

    return pips


def main():
    parser = argparse.ArgumentParser(description='Build pips from mana-master SVGs')
    parser.add_argument('--force', action='store_true',
                        help='Rebuild all symbols from scratch (discard cache)')
    parser.add_argument('--size', type=int, default=128,
                        help='Output PNG size in pixels (default: 128)')
    args = parser.parse_args()

    pips = build_pips(size=args.size, force=args.force)
    print(f"\n[mana] Done! {len(pips)} total symbols available.")

    # Show what we have
    loyalty_keys = [k for k in pips if k.startswith('loyalty')]
    mana_keys = [k for k in pips if len(k) <= 2 and k not in loyalty_keys]
    print(f"  Mana: {sorted(mana_keys)}")
    print(f"  Loyalty: {sorted(loyalty_keys)}")


if __name__ == '__main__':
    main()
